name: Build docker-gitlab image 
on: [push]
jobs:
  docs:
    runs-on: docker
    steps:
      - name: Code herunterladen
        uses: https://code.forgejo.org/senyai/checkout@main
        with:
          ref: 'support-builtin-kas'
